Make location of .xsession-errors configurable
ubuntu/lightdm pull request #287
Opened 2023-01-11 15:38 UTC by nefigtut

LightDM always uses $HOME/.xsession-errors as the log file because it is harcoded. There are several possible reasons for someone to define another location, for example to write it into the RAM or to just have a tidier $HOME-folder.

This is a long-awaited feature, see: https://github.com/canonical/lightdm/issues/95 and https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/1001035

Unfortunately, I have no idea how to fix tests to conform this change. Please, feel free to update as needed.

2023-02-20 19:38 UTC, Soapux reviewed
I think it should be XDG_STATE_HOME or ~/.local/state if not found, which was designed for such log files.  Personally, I think it should probably go in it's on x11 sub directory too since more than one file is created, but it's not mandatory. So ~/.local/state/x11/xsession-errors in that case. I would also remove the dot from the file. Lastly we should probably check if the directories exist and if not, create them with mode 700 to follow the spec.

2023-04-01 20:12 UTC, nefigtut commented
no one from lightdm maintainers/devs has ever reacted to this pr or to #95.
while your suggestion is reasonable, i don't see any sense investing efforts into updating this pr knowing it will be ignored anyway. i give up and version-lock hacked lightdm on my systems.

2023-12-22 02:25 UTC, rozhuk-im commented on src/session.c
> +            priv->log_filename = g_build_filename (g_getenv ("XDG_STATE_HOME"), ".xsession-errors", NULL);
```XDG_CACHE_HOME``` should be here.

2023-12-22 02:28 UTC, rozhuk-im requested changes
copy-paste fix required

2023-12-22 04:13 UTC, rozhuk-im commented
I am not sure that this work: ```XDG_*``` - who set these vars?

2023-12-22 16:34 UTC, madpilot78 commented
> I am not sure that this work: `XDG_*` - who set these vars?

@rozhuk-im It really depends. As far as I understand in most Linux distributions it is systemd setting them nowadays. But these can also be populated by PAM modules or session startup scripts.

In FreeBSD it looks like the magic resides in `/usr/local/etc/xdg`

So my guess is that depending on how they are setup these variable could not be correctly populated when the code actually executes.

2024-12-19 12:41 UTC, nefigtut commented
#335 is a nicer version of this indeed.

2025-03-18 04:12 UTC, ahmubashshir reviewed
IMO, if the log files are in `$XDG_CACHE_HOME` or `$XDG_STATE_HOME`, `.` doesn't need to be in the filename.

2025-12-08 16:14 UTC, closed without merging