Implement FreeBSD vt switching
ubuntu/lightdm pull request #353
Opened 2024-04-21 12:59 UTC by madpilot78

Code provided by fellow FreeBSD committer Tijl Coosemans <tijl@FreeBSD.org>

Ref.: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278457

2024-04-25 13:04 UTC, A1exKH requested changes
Code looks good, please investigate via "build and tests" are failed for this PR.
In logs I can see:

> FAIL: test-power-qt5
====================

> *START-DAEMON

> Command` line: 

> PATH=/__w/lightdm/lightdm/tests/src/.libs:/__w/lightdm/lightdm/tests/src:/__w/lightdm/lightdm/tests/src:/__w/lightdm/lightdm/src:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LD_PRELOAD=/__w/lightdm/lightdm/tests/src/.libs/libsystem.so LD_LIBRARY_PATH=/__w/lightdm/lightdm/liblightdm-gobject/.libs:/__w/lightdm/lightdm/liblightdm-qt/.libs LIGHTDM_TEST_ROOT=/tmp/.r320 DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/dbus-2UHDpgp8ok,guid=551947e0e7f92746299d6c5e66250e4b DBUS_SYSTEM_BUS_ADDRESS=unix:path=/tmp/dbus-PehAOz7f1g,guid=53886e4945be531b200cb63b66250e4b lightdm --debug --cache-dir /tmp/.r320/cache

> Watching process 21181

> RUNNER DAEMON-START

> [+0.00s] DEBUG: Logging to /usr/local/var/log/lightdm/lightdm.log
> [+0.00s] DEBUG: Starting Light Display Manager 1.32.0, UID=0 PID=21181
> [+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
> [+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
> [+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
> [+0.00s] DEBUG: Loading configuration from /usr/local/etc/lightdm/lightdm.conf
> [+0.00s] DEBUG: Registered seat module local
> [+0.00s] DEBUG: Registered seat module xremote
> [+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
> [+0.00s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
> [+0.00s] DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
> [+0.00s] DEBUG: Monitoring logind for seats
> [+0.00s] DEBUG: New seat added from logind: seat0
[+0.00s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.00s] DEBUG: Seat seat0: Starting
[+0.00s] DEBUG: Seat seat0: Creating greeter session
[+0.00s] DEBUG: Seat seat0: Creating display server of type x
[+0.00s] DEBUG: Seat seat0: Starting local X display
[+0.00s] DEBUG: XServer 0: Logging to /usr/local/var/log/lightdm/x-0.log
[+0.00s] DEBUG: XServer 0: Writing X server authority to /usr/local/var/run/lightdm/root/:0
[+0.00s] DEBUG: XServer 0: Launching X Server
[+0.00s] DEBUG: Launching process 21187: /__w/lightdm/lightdm/tests/src/X :0 -seat seat0 -auth /usr/local/var/run/lightdm/root/:0 -nolisten tcp
[+0.00s] DEBUG: XServer 0: Waiting for ready signal from X server :0
[+0.00s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
XSERVER-0 START SEAT=seat0
Command line: PATH=/__w/lightdm/lightdm/tests/src/.libs:/__w/lightdm/lightdm/tests/src:/__w/lightdm/lightdm/tests/src:/__w/lightdm/lightdm/src:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LD_PRELOAD=/__w/lightdm/lightdm/tests/src/.libs/libsystem.so LD_LIBRARY_PATH=/__w/lightdm/lightdm/liblightdm-gobject/.libs:/__w/lightdm/lightdm/liblightdm-qt/.libs LIGHTDM_TEST_ROOT=/tmp/.r320 DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/dbus-2UHDpgp8ok,guid=551947e0e7f92746299d6c5e66250e4b DBUS_SYSTEM_BUS_ADDRESS=unix:path=/tmp/dbus-PehAOz7f1g,guid=53886e4945be531b200cb63b66250e4b lightdm --debug --cache-dir /tmp/.r320/cache
Events:
    *START-DAEMON
    RUNNER DAEMON-START
    XSERVER-0 START SEAT=seat0
    ^^^ expected "XSERVER-0 START VT=7 SEAT=seat0"
Sending SIGTERM to process 21181
[+0.01s] DEBUG: Got signal 15 from process 21177
[+0.01s] DEBUG: Caught Terminated signal, shutting down
[+0.01s] DEBUG: Stopping display manager
[+0.01s] DEBUG: Seat seat0: Stopping
[+0.01s] DEBUG: Seat seat0: Stopping display server
[+0.01s] DEBUG: Sending signal 15 to process 21187
[+0.01s] DEBUG: Seat seat0: Stopping session
[+0.01s] DEBUG: Seat seat0: Session stopped
[+0.01s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1001 added
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1002 added
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1003 added
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1004 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1005 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1006 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1007 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1008 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1009 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1010 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1011 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1012 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1013 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1014 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1015 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1016 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1017 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1018 added
[+0.02s] DEBUG: User /org/freedesktop/Accounts/User1019 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1020 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1021 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1022 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1023 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1024 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1025 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1026 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1027 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1028 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1029 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1030 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1031 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1032 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1033 added
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1034 added
[+0.04s] DEBUG: Process 21187 exited with return value 0
[+0.04s] DEBUG: XServer 0: X server stopped
[+0.04s] DEBUG: XServer 0: Removing X server authority /usr/local/var/run/lightdm/root/:0
[+0.04s] DEBUG: Seat seat0: Display server stopped
[+0.04s] DEBUG: Seat seat0: Stopped
[+0.04s] DEBUG: Display manager stopped
[+0.04s] DEBUG: Stopping daemon
[+0.04s] DEBUG: User /org/freedesktop/Accounts/User0 added
[+0.04s] DEBUG: User /org/freedesktop/Accounts/User100 added
[+0.04s] DEBUG: Exiting with return value 0
Process 21181 exited with status 0
FAIL test-power-qt5 (exit status: 1)

> Error: Process completed with exit code 1.

2024-04-28 14:49 UTC, madpilot78 commented
@A1exKH 

The same failure is happening on the head of the main branch, so I guess they are unrelated to this change.

2026-07-06 19:11 UTC, JPeisach approved these changes
Actually, locally merging the branch makes the test pass count go from 35 -> 36.

But most of the tests are failing because it strictly expects VT 7..

As for the Linux side of things, this shouldn't affect anything. I think the ifdef macros work.

2026-07-30 18:22 UTC, jpeisach commented
Since this PR has no issues, and it's been sitting for over 2 years, I'd say LGTM.

2026-07-30 18:22 UTC, merged